#!/bin/bash

# Copyright (C) 2019 Intel Corporation
# SPDX-License-Identifier: BSD-3-Clause

source /opt/bootstrap/functions

kernel_params=$(cat /proc/cmdline)
echo "The Device VM got alive and ran init at $(date -Iminutes)" > /mnt/root/alive.txt
sshpass -p "password" scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null /mnt/root/alive.txt demo_pxe_vm@192.168.127.11:/tmp/alive-$(date -Iminutes).txt

if [[ $kernel_params = *"liveOs="* ]]; then

	if [[ $kernel_params = *"bootstrap="* ]]; then
		tmp="${kernel_params##*bootstrap=}"
		param_bootstrap="${tmp%% *}"
	else
		echo "'bootstrap' kernel parameter missing!" 2>&1 | tee -a /dev/tty0
		sleep 30
		reboot
	fi


	if [[ $kernel_params = *"httpserver="* ]]; then
		tmp="${kernel_params##*httpserver=}"
		param_httpserver="${tmp%% *}"
	else
		echo "'httpserver' kernel parameter missing!" 2>&1 | tee -a /dev/tty0
		sleep 30
		reboot
	fi

	wget -O - ${param_bootstrap} 2> /dev/tty0 | bash -s - $param_httpserver

else
	/opt/bootstrap/bootstrap
fi
